[package]
name = "core-p2p"
version = "0.1.0"
authors = ["piaoliu <441594700@qq.com>"]

[dependencies]
libp2p = { git = "https://github.com/libp2p/rust-libp2p" }
futures = "0.1"
tokio = "0.1"
bytes = "0.4.10"
byteorder = "1.0.0"
parking_lot = "0.7"
log = "0.4.6"